[package]
name = "sadapp-host-agent"
version = "0.2.5"
edition = "2024"
license = "Apache-2.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = "0.29"
reqwest = { version = "0.12", features = ["blocking", "json", "rustls-tls"], default-features = false }
ring = "0.17.14"
ctrlc = { version = "3.4", features = ["termination"] }
